import { Geist, Geist_Mono, Roboto } from "next/font/google";

import "./globals.css";
import styles from "./admin.module.css";
import Providers from "./redux/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bonadia Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
